package similarities;

public enum SimEnum {
    PEARSON_CORRELATION,
    SPEARMAN_CORRELATION,
    MULTIPOLE,
    EUCLIDEAN_SIMILARITY,
    MANHATTAN_SIMILARITY,
    CHEBYSHEV_SIMILARITY,
    TOTAL_CORRELATION
}


